motivation_quotes = [
"Push yourself, because no one else is going to do it for you.",
"Success doesn't just find you. You have to go out and get it.",
"Great things never come from comfort zones.",
"Dream it. Wish it. Do it.",
"Do something today that your future self will thank you for.",
"Little things make big days.",
"It's going to be hard, but hard does not mean impossible.",
"Don't wait for opportunity. Create it.",
"Sometimes later becomes never. Do it now.",
"Success is what comes after you stop making excuses.",
"Work hard in silence, let success make the noise.",
"Dream bigger. Do bigger.",
"Don't stop until you're proud.",
"Wake up with determination, go to bed with satisfaction.",
"Do what is right, not what is easy.",
"The harder you work for something, the greater you'll feel when you achieve it.",
"Don't limit your challenges. Challenge your limits.",
"Success begins with self-discipline.",
"Stay focused and never give up.",
"Your only limit is your mind.",
"Small progress is still progress.",
"Make it happen. Shock everyone.",
"Be stronger than your excuses.",
"Believe in yourself and all that you are.",
"The key to success is to start before you're ready.",
"Failure is not the opposite of success. It is part of success.",
"Discipline is choosing between what you want now and what you want most.",
"Hard work beats talent when talent doesn't work hard.",
"Success is built on consistency.",
"Keep going. Everything you need will come to you.",
"Your future is created by what you do today.",
"Don't watch the clock. Do what it does. Keep going.",
"The secret of getting ahead is getting started.",
"Stay positive, work hard, make it happen.",
"Every accomplishment starts with the decision to try.",
"You don't have to be great to start, but you have to start to be great.",
"Action is the foundational key to success.",
"Success usually comes to those who are too busy to be looking for it.",
"Opportunities don't happen. You create them.",
"The harder the struggle, the more glorious the triumph.",
"Don't be afraid to give up the good to go for the great.",
"Believe you can and you're halfway there.",
"Success is not for the lazy.",
"Make today count.",
"Do it with passion or not at all.",
"Turn your dreams into plans.",
"Consistency is what transforms average into excellence.",
"Stay hungry for success.",
"Be the hardest worker in the room.",
"Success loves preparation.",
"Motivation gets you started, discipline keeps you going.",
"Never quit. Great things take time.",
"Push past your limits.",
"Focus on your goal, not the obstacles.",
"The best view comes after the hardest climb.",
"Strive for progress, not perfection.",
"Be fearless in pursuit of what sets your soul on fire.",
"Start small but dream big.",
"Your dreams don't work unless you do.",
"Great things take time and patience.",
"Your potential is endless.",
"Turn setbacks into comebacks.",
"Rise above the storm.",
"Stay committed to your goals.",
"Make yourself proud.",
"Success starts with self-belief.",
"Chase progress, not comfort.",
"Never settle for less than your best.",
"Be proud of how far you have come.",
"Work until your idols become your rivals.",
"One day or day one. You decide.",
"Don't stop when you're tired. Stop when you're done.",
"Be stronger than your strongest excuse.",
"Push through the pain.",
"Success is earned daily.",
"Stay focused on your mission.",
"The only way to fail is to quit.",
"Success rewards persistence.",
"Your effort determines your outcome.",
"Turn your pain into power.",
"Dream big and dare to fail.",
"Keep climbing.",
"Stay determined.",
"Create the life you want.",
"Build your own dreams.",
"Work smart and hard.",
"Believe in your journey.",
"Success favors the brave.",
"Stay hungry for improvement.",
"Let your ambition drive you.",
"Progress requires patience.",
"Rise and grind.",
"Stay unstoppable.",
"Make your passion your purpose.",
"Your dreams are worth the effort.",
"Keep moving forward.",
"Fight for your goals.",
"Commit to the process.",
"Never doubt your ability.",
"Stay disciplined.",
"Stay focused and execute.",
"Turn vision into reality.",
"Create your own path.",
"Success is built daily.",
"Be your own inspiration.",
"Greatness requires sacrifice.",
"Push forward relentlessly.",
"Hard work builds character.",
"Stay resilient.",
"Believe in your grind.",
"Every step matters.",
"Your work will pay off.",
"Stay patient and persistent.",
"Dream. Plan. Execute.",
"Be unstoppable.",
"Focus fuels success.",
"Work harder than yesterday.",
"Rise above mediocrity.",
"Be bold in your ambition.",
"Turn effort into excellence.",
"Stay committed to greatness.",
"Focus on improvement.",
"Never stop learning.",
"Success requires courage.",
"Make progress every day.",
"Stay consistent.",
"Believe in the process.",
"Take action now.",
"Create unstoppable momentum.",
"Invest in yourself.",
"Stay determined.",
"Focus on your mission.",
"Keep chasing excellence.",
"Build discipline daily.",
"Embrace the challenge.",
"Work until success notices you.",
"Push beyond comfort.",
"Stay strong.",
"Chase greatness.",
"Believe in growth.",
"Stay focused on your path.",
"Work with purpose.",
"Progress over excuses.",
"Rise above limits.",
"Stay driven.",
"Make success your habit.",
"Outwork your competition.",
"Stay hungry for growth.",
"Let your work speak.",
"Stay relentless.",
"Rise stronger.",
"Push the limits.",
"Focus and finish.",
"Keep building your future.",
"Success demands effort.",
"Keep improving daily.",
"Strive for greatness.",
"Stay fearless.",
"Work beyond expectations.",
"Stay motivated daily.",
"Chase your passion.",
"Focus on the journey.",
"Stay determined every day.",
"Turn effort into achievement.",
"Work with intensity.",
"Build unstoppable discipline.",
"Stay focused and fearless.",
"Keep your goals in sight.",
"Rise above challenges.",
"Stay resilient and strong.",
"Make your dreams happen.",
"Work hard every day.",
"Keep climbing higher.",
"Success starts with effort.",
"Stay motivated always.",
"Push beyond limits.",
"Be unstoppable today.",
"Make excellence a habit.",
"Focus on what matters.",
"Keep pushing forward.",
"Rise with determination.",
"Stay committed to success.",
"Work for your dreams.",
"Stay driven every day.",
"Believe in your grind.",
"Turn dreams into action.",
"Stay motivated and strong.",
"Keep striving for better.",
"Make every day count.",
"Stay determined to succeed.",
"Rise above doubts.",
"Push your boundaries.",
"Work hard, dream big.",
"Stay relentless in pursuit.",
"Focus on success daily.",
"Be stronger than yesterday.",
"Stay ambitious always.",
"Keep chasing your goals.",
"Rise to every challenge.",
"Work with dedication.",
"Stay focused and driven.",
"Make progress happen.",
"Stay determined to win."
]

inspiration_quotes = [
"Believe you can and you're halfway there.",
"Your life becomes what you believe.",
"Turn your wounds into wisdom.",
"In the middle of difficulty lies opportunity.",
"Start where you are. Use what you have. Do what you can.",
"Every day is a second chance.",
"Be the change that you wish to see in the world.",
"What you do today can improve all your tomorrows.",
"Act as if what you do makes a difference. It does.",
"Happiness is not by chance but by choice.",
"Keep your face always toward the sunshine.",
"It always seems impossible until it's done.",
"Do not wait for the perfect moment. Take the moment and make it perfect.",
"The best way to predict the future is to create it.",
"Your story is still being written.",
"Difficult roads often lead to beautiful destinations.",
"Start each day with a grateful heart.",
"Believe in the power of your dreams.",
"Rise above the storm and you will find the sunshine.",
"The best view comes after the hardest climb.",
"Every accomplishment starts with the decision to try.",
"Stay patient and trust your journey.",
"You are stronger than you think.",
"Let your dreams be bigger than your fears.",
"Stars can't shine without darkness.",
"Don't be afraid to shine.",
"Growth begins at the end of your comfort zone.",
"Your potential is endless.",
"Chase your dreams with courage.",
"Keep moving forward no matter what.",
"Let your hope be bigger than your fear.",
"Every moment is a fresh beginning.",
"Be the light that helps others see.",
"Shine bright even on your darkest days.",
"Believe something wonderful is about to happen.",
"Small steps every day lead to big results.",
"Let your heart guide your journey.",
"You are capable of amazing things.",
"Your dreams are closer than you think.",
"Choose courage over comfort.",
"Keep believing in yourself.",
"The best things in life take time.",
"Your courage will lead the way.",
"Trust the timing of your life.",
"Stay hopeful and strong.",
"Every challenge makes you stronger.",
"Keep your dreams alive.",
"Let your passion inspire others.",
"Never stop believing.",
"You have the power to create change.",
"Your strength is greater than your struggle.",
"Be proud of how far you've come.",
"The journey is as important as the destination.",
"Hope is stronger than fear.",
"Every sunrise brings new hope.",
"Believe in the beauty of your dreams.",
"Let kindness be your strength.",
"The world needs your light.",
"Make today meaningful.",
"Trust yourself.",
"Your journey matters.",
"Stay positive and hopeful.",
"Your future is bright.",
"Believe in endless possibilities.",
"Find joy in small moments.",
"Let gratitude guide your day.",
"Stay inspired.",
"Your dreams matter.",
"Be inspired by your own story.",
"Find beauty in every day.",
"Let your soul shine.",
"Stay curious and hopeful.",
"Make your life inspiring.",
"Follow your heart.",
"Every step forward counts.",
"Believe in better days.",
"Choose hope every day.",
"Inspire others by being yourself.",
"Your spirit is powerful.",
"Stay true to your dreams.",
"Let your courage inspire others.",
"Dream with open eyes.",
"Believe in tomorrow.",
"Keep shining.",
"Hope fuels progress.",
"Inspiration is everywhere.",
"Let your dreams guide you.",
"Stay positive always.",
"Be inspired by life.",
"Trust your potential.",
"Be fearless in hope.",
"Believe in good things ahead.",
"Stay optimistic.",
"Find inspiration in challenges.",
"Keep believing in magic.",
"Hope lights the way.",
"Believe in endless growth.",
"Inspire yourself daily.",
"See possibilities everywhere.",
"Let your dreams lead you.",
"Stay inspired every day.",
"Your heart knows the way.",
"Believe in better futures.",
"Be a source of inspiration.",
"Trust your journey.",
"Inspire with kindness.",
"Keep dreaming big.",
"Believe in miracles.",
"Your light matters.",
"Stay hopeful always.",
"Inspire greatness.",
"Let positivity lead.",
"Find strength in hope.",
"Believe in yourself daily.",
"Stay uplifted.",
"Dream fearlessly.",
"Be inspired by challenges.",
"Hope drives success.",
"Let joy inspire you.",
"Believe in brighter days.",
"Inspiration starts within.",
"Trust your inner voice.",
"Find beauty in growth.",
"Be inspired by progress.",
"Stay hopeful in every season.",
"Believe in endless possibilities.",
"Keep your dreams alive.",
"Hope never fades.",
"Inspire with courage.",
"Let hope guide you.",
"Dream without limits.",
"Stay inspired and strong.",
"Believe in growth.",
"Hope creates change.",
"Let inspiration guide you.",
"Stay positive and brave.",
"Believe in yourself always.",
"Inspiration grows daily.",
"Hope brings strength.",
"Dream boldly.",
"Stay hopeful forever.",
"Inspire yourself every morning.",
"Believe in the good.",
"Let hope win.",
"Stay inspired by life.",
"Believe in progress.",
"Hope builds resilience.",
"Be inspired by effort.",
"Dream endlessly.",
"Stay hopeful daily.",
"Believe in purpose.",
"Inspire through action.",
"Let hope grow.",
"Dream courageously.",
"Stay uplifted daily.",
"Believe in tomorrow always.",
"Inspire with positivity.",
"Hope brings courage.",
"Dream passionately.",
"Stay inspired constantly.",
"Believe in your light.",
"Inspire growth.",
"Hope creates opportunity.",
"Dream persistently.",
"Stay inspired forever.",
"Believe in new beginnings.",
"Inspire happiness.",
"Hope fuels dreams.",
"Dream confidently.",
"Stay hopeful always.",
"Believe in brighter futures.",
"Inspire courage.",
"Hope empowers progress.",
"Dream fearlessly always.",
"Stay inspired by hope.",
"Believe in strength.",
"Inspire kindness daily.",
"Hope creates possibility.",
"Dream without fear.",
"Stay hopeful endlessly.",
"Believe in inspiration.",
"Inspire others through hope.",
"Hope grows courage.",
"Dream endlessly forward.",
"Stay inspired every moment.",
"Believe in positive change.",
"Inspire strength daily.",
"Hope creates light.",
"Dream beyond limits.",
"Stay hopeful and bright.",
"Believe in great possibilities.",
"Inspire your journey.",
"Hope builds dreams.",
"Dream toward greatness.",
"Stay inspired forever.",
"Inspiration grows through action.",
"Hope leads to new beginnings.",
"Dream big and stay inspired.",
"Believe in the power of change.",
"Let inspiration guide your future."
]

love_quotes = [
"Where there is love, there is life.",
"You are my today and all of my tomorrows.",
"Love is composed of a single soul inhabiting two bodies.",
"Love is not what you say. Love is what you do.",
"Love is when another person's happiness is your happiness.",
"The best thing to hold onto in life is each other.",
"Love is the bridge between two hearts.",
"A loving heart is the truest wisdom.",
"You make my world brighter.",
"Love is friendship set on fire.",
"Love makes ordinary moments extraordinary.",
"True love never fades.",
"In your smile I see something more beautiful than stars.",
"Love grows stronger with time.",
"The heart wants what it wants.",
"Love is a language spoken by everyone.",
"Love is the beauty of the soul.",
"You are the reason for my smile.",
"Love doesn't need a reason.",
"Love begins with a smile.",
"Love makes life meaningful.",
"The greatest happiness is love.",
"Your love completes me.",
"Love is the closest thing we have to magic.",
"To love and be loved is everything.",
"Love is the heartbeat of life.",
"Love is the light in the darkness.",
"You are my favorite hello.",
"Love is endless.",
"Love makes the world beautiful.",
"My heart is where you are.",
"Every love story is beautiful.",
"Love grows where kindness lives.",
"Love brings warmth to the soul.",
"Love makes life magical.",
"You are my happy place.",
"Love is a beautiful journey.",
"Love shines through every moment.",
"Love is a gentle promise.",
"Love connects hearts forever.",
"Love is the sweetest feeling.",
"Love brings peace to the heart.",
"Love is the greatest gift.",
"Love is stronger than fear.",
"Love grows through understanding.",
"Love is patient and kind.",
"Love brightens every day.",
"Love makes the impossible possible.",
"Love is a beautiful adventure.",
"Love creates beautiful memories.",
"Love is the soul's happiness.",
"Love fills life with joy.",
"Love brings two hearts together.",
"Love gives life meaning.",
"Love is the music of the heart.",
"Love is the warmth of life.",
"Love turns moments into memories.",
"Love is the light of life.",
"Love blossoms with care.",
"Love grows through trust.",
"Love is the sweetest connection.",
"Love paints life with happiness.",
"Love strengthens every bond.",
"Love is a beautiful emotion.",
"Love shines in small moments.",
"Love grows through patience.",
"Love brings comfort.",
"Love is the soul's language.",
"Love inspires kindness.",
"Love builds beautiful futures.",
"Love fills hearts with peace.",
"Love brings endless joy.",
"Love connects souls.",
"Love is a gentle feeling.",
"Love is life's greatest treasure.",
"Love grows stronger every day.",
"Love fills the heart with warmth.",
"Love is the power of the heart.",
"Love lights the path of life.",
"Love brings harmony.",
"Love grows through care.",
"Love is pure happiness.",
"Love spreads positivity.",
"Love brings people together.",
"Love is timeless.",
"Love creates happiness.",
"Love is the heart's joy.",
"Love inspires smiles.",
"Love grows endlessly.",
"Love makes hearts bloom.",
"Love creates strong bonds.",
"Love is the beauty of life.",
"Love brightens every moment.",
"Love is a beautiful connection.",
"Love grows with time.",
"Love inspires happiness.",
"Love fills life with warmth.",
"Love is the heart's melody.",
"Love strengthens relationships.",
"Love makes life colorful.",
"Love brings peace.",
"Love fills the world with joy.",
"Love connects hearts deeply.",
"Love spreads kindness.",
"Love makes every day better.",
"Love is the greatest joy.",
"Love builds happiness.",
"Love lights every path.",
"Love grows through compassion.",
"Love is endless happiness.",
"Love creates beautiful moments.",
"Love brings smiles.",
"Love strengthens the soul.",
"Love fills life with beauty.",
"Love inspires warmth.",
"Love creates joy everywhere.",
"Love spreads light.",
"Love connects hearts forever.",
"Love is the heart's strength.",
"Love brings harmony to life.",
"Love is pure joy.",
"Love creates unforgettable memories.",
"Love inspires laughter.",
"Love grows through trust and care.",
"Love brings calm to the soul.",
"Love makes hearts glow.",
"Love spreads happiness.",
"Love fills life with meaning.",
"Love inspires hope.",
"Love builds lasting bonds.",
"Love makes the heart sing.",
"Love grows through kindness.",
"Love is life's sweetest gift.",
"Love creates beautiful dreams.",
"Love strengthens every connection.",
"Love inspires joy.",
"Love fills hearts with warmth.",
"Love brings people closer.",
"Love is the light of happiness.",
"Love grows through patience and care.",
"Love inspires beautiful moments.",
"Love makes every moment special.",
"Love creates magical memories.",
"Love spreads warmth.",
"Love fills life with laughter.",
"Love inspires connection.",
"Love grows stronger with trust.",
"Love brings peace and happiness.",
"Love is the beauty of the heart.",
"Love creates harmony.",
"Love inspires kindness everywhere.",
"Love makes life meaningful.",
"Love builds beautiful stories.",
"Love spreads joy everywhere.",
"Love fills the world with warmth.",
"Love inspires happiness every day.",
"Love strengthens hearts.",
"Love creates a beautiful life.",
"Love inspires smiles everywhere.",
"Love fills life with sweetness.",
"Love grows endlessly with care.",
"Love inspires bright days.",
"Love makes hearts shine.",
"Love spreads warmth everywhere.",
"Love fills life with joy and peace.",
"Love creates beautiful connections.",
"Love inspires happiness always.",
"Love fills the heart with light.",
"Love grows stronger every moment.",
"Love inspires endless joy.",
"Love creates wonderful memories.",
"Love brings hearts together.",
"Love spreads kindness everywhere.",
"Love fills the soul with happiness.",
"Love inspires peaceful hearts.",
"Love makes life beautiful.",
"Love creates lasting happiness.",
"Love fills every moment with joy.",
"Love inspires warm hearts.",
"Love spreads joy across life.",
"Love builds a happy future.",
"Love creates endless smiles.",
"Love inspires beautiful hearts.",
"Love fills life with hope.",
"Love spreads happiness everywhere.",
"Love makes the world brighter.",
"Love inspires joyful moments.",
"Love grows through compassion.",
"Love creates lasting peace.",
"Love fills hearts with beauty.",
"Love inspires happiness forever.",
"Love grows deeper with every shared moment.",
"Love is the quiet comfort of being understood.",
"Love is two hearts walking the same path.",
"Love is the warmth of holding someone close.",
"Love makes ordinary days extraordinary.",
"Love is the smile that appears because of someone.",
"Love grows stronger with every challenge.",
"Love is caring even when it's difficult.",
"Love is the sweetest part of life.",
"Love shines brightest in simple moments.",
"Love is the happiness of togetherness."
]

humor_quotes = [
"I'm not lazy, I'm just on energy-saving mode.",
"Life is short. Smile while you still have teeth.",
"I followed my heart and it led me to the fridge.",
"My wallet is like an onion. Opening it makes me cry.",
"I need six months of vacation twice a year.",
"I'm not arguing, I'm just explaining why I'm right.",
"I'm multitasking: I can listen, ignore, and forget at the same time.",
"I'm not weird, I'm limited edition.",
"My brain has too many tabs open.",
"I love sleep because it's like a time machine to breakfast.",
"I put the pro in procrastination.",
"My bed is a magical place where I suddenly remember everything I forgot to do.",
"I'm on a seafood diet. I see food and I eat it.",
"If Monday had a face, I would punch it.",
"Some people graduate with honors, I am just honored to graduate.",
"My phone battery lasts longer than my motivation.",
"I'm not short, I'm concentrated awesome.",
"I don't need a hair stylist. My pillow gives me a new hairstyle every morning.",
"Chocolate doesn't ask questions. Chocolate understands.",
"I'm not lazy. I'm on power-saving mode.",
"Common sense is like deodorant. People who need it most never use it.",
"Why fall in love when you can fall asleep?",
"I'm not late, everyone else is just early.",
"I love deadlines. I like the whooshing sound they make as they fly by.",
"I don't rise and shine. I caffeinate and hope for the best.",
"If stress burned calories, I'd be a supermodel.",
"I'm not great at advice. Can I interest you in sarcasm?",
"I came. I saw. I made it awkward.",
"My brain is 80% song lyrics.",
"I'm not clumsy. The floor just hates me.",
"My hobbies include eating and complaining that I'm getting fat.",
"I'm not ignoring you, I'm just prioritizing my nap.",
"Life is like a sandwich. The more you add, the better it gets.",
"I'm not lazy, I'm just highly motivated to do nothing.",
"My favorite exercise is a cross between a lunge and a crunch. I call it lunch.",
"I'm not weird, I'm just more creative than average.",
"My diet plan is simple: eat everything.",
"Why do they call it rush hour when nothing moves?",
"I don't need a therapist, I just need a vacation.",
"I don't trip. I do random gravity checks.",
"I'm not superstitious, but I am a little stitious.",
"I'm not lazy, I'm in energy-saving mode.",
"My memory is so bad it makes me forget things I just forgot.",
"I finally got eight hours of sleep. It took me three days.",
"I don't need a motivational quote. I need coffee.",
"I'm not arguing, I'm just passionately explaining my opinion.",
"I wish everything in life was as easy as gaining weight.",
"I'm not addicted to my phone. We're just in a committed relationship.",
"I don't need anger management. I need people to stop annoying me.",
"I talk to myself because sometimes I need expert advice.",
"I'm not lazy, I just rest before I get tired.",
"I'm not late. Time is just moving too fast.",
"I don't need a gym membership. I run out of money every month.",
"I'm not always funny, sometimes I'm asleep.",
"I work out by running out of patience.",
"I would lose weight but I hate losing.",
"I don't need a new hairstyle, I need a new life.",
"I don't suffer from insanity, I enjoy every minute of it.",
"I don't need a GPS. My mistakes guide me.",
"I started out with nothing and still have most of it.",
"I'm not crazy. My reality is just different.",
"I'm not a morning person or a night owl. I'm some form of permanently exhausted pigeon.",
"I'm not lazy, I just really enjoy doing nothing.",
"I used to think I was indecisive, but now I'm not sure.",
"I'm not arguing, I'm just explaining why I'm right again.",
"I'm not bossy, I just know what you should be doing.",
"I'm not shy. I'm just holding back my awesomeness.",
"I'm not lazy. I'm on break.",
"I'm not rude. I'm honest.",
"I'm not dramatic. I'm just expressive.",
"I'm not ignoring you. I'm just pretending you don't exist.",
"I'm not lost. I'm exploring.",
"I'm not confused. I'm creatively thinking.",
"I'm not overthinking. I'm just thinking too much.",
"I'm not unlucky. I'm just extra challenged.",
"I'm not slow. I'm just thinking deeply.",
"I'm not forgetful. I'm just remembering selectively.",
"I'm not stubborn. I'm just determined.",
"I'm not sarcastic. I'm just intelligent beyond your understanding.",
"I'm not quiet. I just don't talk to everyone.",
"I'm not bored. I'm creatively resting.",
"I'm not tired. I'm just energy-efficient.",
"I'm not messy. I'm organizationally challenged.",
"I'm not unlucky. I just have adventurous luck.",
"I'm not procrastinating. I'm prioritizing future stress.",
"I'm not lazy. I'm conserving energy.",
"I'm not distracted. I'm just multi-thinking.",
"I'm not sleeping. I'm practicing for death.",
"I'm not hungry. I'm just food motivated.",
"I'm not clumsy. I'm dancing with gravity.",
"I'm not short. I'm fun-sized.",
"I'm not late. I'm fashionably delayed.",
"I'm not weird. I'm a limited edition.",
"I'm not talking too much. You're just listening too slowly.",
"I'm not complaining. I'm explaining the situation.",
"I'm not dramatic. I'm just enthusiastic.",
"I'm not overreacting. I'm reacting properly.",
"I'm not grumpy. I'm just caffeine deprived.",
"I'm not funny. I'm accidentally hilarious.",
"I'm not confused. I'm just thinking creatively.",
"I'm not ignoring responsibilities. I'm delaying them.",
"I'm not lazy. I'm productivity resistant.",
"I'm not unlucky. I'm statistically challenged.",
"I'm not awkward. I'm socially creative.",
"I'm not serious. I'm humorously intelligent.",
"I'm not difficult. I'm selectively cooperative.",
"I'm not picky. I just know what I want.",
"I'm not irresponsible. I'm adventure friendly.",
"I'm not complicated. I'm just interesting.",
"I'm not impatient. I just hate waiting.",
"I'm not careless. I'm carefree.",
"I'm not overthinking. I'm thinking deeply.",
"I'm not quiet. I'm observing.",
"I'm not lost. I'm taking the scenic route.",
"I'm not lazy. I'm restfully productive.",
"I'm not stressed. I'm aggressively relaxed.",
"I'm not tired. I'm energy saving.",
"I'm not late. I'm time flexible.",
"I'm not weird. I'm unique.",
"I'm not awkward. I'm entertaining.",
"I'm not shy. I'm mysterious.",
"I'm not random. I'm creative.",
"I'm not distracted. I'm imaginative.",
"I'm not messy. I'm creatively organized.",
"I'm not loud. I'm enthusiastic.",
"I'm not crazy. I'm fun.",
"I'm not dramatic. I'm passionate.",
"I'm not stubborn. I'm persistent.",
"I'm not slow. I'm thoughtful.",
"I'm not clumsy. I'm adventurous.",
"I'm not forgetful. I'm memory flexible.",
"I'm not silly. I'm joyful.",
"I'm not bored. I'm imaginative.",
"I'm not quiet. I'm peaceful.",
"I'm not lazy. I'm relaxed.",
"I'm not angry. I'm expressive.",
"I'm not difficult. I'm challenging.",
"I'm not picky. I'm selective.",
"I'm not rude. I'm direct.",
"I'm not lazy. I'm comfortable.",
"I'm not serious. I'm cheerful.",
"I'm not dramatic. I'm expressive.",
"I'm not quiet. I'm thoughtful.",
"I'm not strange. I'm special.",
"I'm not slow. I'm careful.",
"I'm not loud. I'm excited.",
"I'm not random. I'm spontaneous.",
"I'm not lost. I'm curious.",
"I'm not lazy. I'm resting.",
"I'm not weird. I'm interesting.",
"I'm not shy. I'm selective.",
"I'm not quiet. I'm observing life.",
"I'm not distracted. I'm exploring ideas.",
"I'm not messy. I'm creative.",
"I'm not dramatic. I'm lively.",
"I'm not serious. I'm playful.",
"I'm not silent. I'm thinking.",
"I'm not different. I'm original.",
"I'm not slow. I'm thoughtful.",
"I'm not crazy. I'm imaginative.",
"I'm not lazy. I'm relaxed.",
"I'm not awkward. I'm unique.",
"I'm not tired. I'm peaceful.",
"I'm not boring. I'm calm.",
"I'm not loud. I'm expressive.",
"I'm not difficult. I'm complex.",
"I'm not strange. I'm rare.",
"I'm not ordinary. I'm extraordinary.",
"I'm not average. I'm interesting.",
"I'm not simple. I'm creative.",
"I'm not quiet. I'm thoughtful.",
"I'm not weird. I'm wonderful.",
"I'm not random. I'm spontaneous.",
"I'm not dull. I'm peaceful.",
"I'm not boring. I'm relaxed.",
"I'm not strange. I'm special.",
"I'm not quiet. I'm observing.",
"I'm not slow. I'm careful.",
"I'm not loud. I'm excited.",
"I'm not messy. I'm creative.",
"I'm not random. I'm fun.",
"I'm not lazy. I'm resting.",
"I'm not boring. I'm calm.",
"I'm not quiet. I'm thoughtful.",
"I'm not weird. I'm unique.",
"I'm not tired. I'm relaxed.",
"I'm not dramatic. I'm expressive.",
"I'm not strange. I'm interesting.",
"I'm not boring. I'm peaceful.",
"I'm not lazy. I'm comfortable.",
"I'm not weird. I'm creative.",
"I'm not dull. I'm calm.",
"I'm not random. I'm spontaneous.",
"I'm not quiet. I'm thoughtful.",
"Why do they call it beauty sleep when you wake up looking worse?",
"I'm not lazy, I'm just in my power-saving mode.",
"My brain is like the internet: 19 tabs open, 3 frozen, and I have no idea where the music is coming from.",
"I wish my bank account had the same energy as my hunger.",
"Life is too short to take seriously all the time.",
"If life gives you lemons, ask for salt and tequila.",
"I thought about going on a diet, but I hate losing.",
"I'm not addicted to coffee, we're just in a committed relationship.",
"My favorite childhood memory is not paying bills.",
"I'm not saying I'm lazy, but my phone battery lasts longer than my motivation.",
"I finally got my life together… but then it fell apart again.",
"I'm not clumsy, the floor just needed a hug.",
"I tried to be normal once. Worst two minutes of my life.",
"I don't snore, I dream I'm a motorcycle.",
"I need a six-month holiday twice a year.",
"Sometimes I pretend to be normal, but it gets boring quickly."
]